### PR TITLE
allow enabling Django's SECURE_SSL_REDIRECT setting

### PR DESCRIPTION
**Pull request by tobiasmcnulty**

### CODE REVIEW

**Comment by smn** [comment]
🎉 thanks!

**Comment by smn** [comment]
ah looks like there's a few changes we've applied in `praekeltfoundation/rapidpro-docker` that haven't been applied here. Let me see if I can do a PR for those.

**Comment by tobiasmcnulty** [comment]
re: the build failure? Cool, thanks. Off topic, but how have you been dealing w/lack of tags on https://github.com/rapidpro/rapidpro?

**Comment by smn** [comment]
@tobiasmcnulty we've been dealing with them with the changes I've submitted in https://github.com/rapidpro/rapidpro-docker/pull/18

**Comment by smn** [comment]
You'll notice that we've been pushing our own tags to https://github.com/praekeltfoundation/rapidpro/releases which are released here: https://hub.docker.com/r/praekeltfoundation/rapidpro/tags/. The strategy we're going with is that we're always on digit ahead of whatever rapidpro/rapidpro is at suffixed with a `p<number>` indicating our version number.

**Comment by smn** [comment]
@tobiasmcnulty sorry this fell off my radar for a bit. I'm 👍 on this change though but I think the latest changes from master need to be merged in before this'll apply cleanly.

**Pull request closed without merging**
