### PR TITLE
Automate the building of tagged images using Travis (#1)

### PR DESCRIPTION
**Pull request by smn**
On each build, pull down the latest tagged image from nyaruka/rapidpro, build it, run migrations, collectstatic, compress and a make sure Django is reporting no issues.

When completed, push to the public docker registry tagged with the tag from github.

### CODE REVIEW

**Comment by smn** [comment]
I've left the image name as `sdehaan/rapidpro` for now, we could use the Travis environment variable for the `<account>/<repo>` combination but we may want to release this on Docker Hub as `rapidpro/rapidpro` instead of `rapidpro/rapidpro-docker`.

**Comment by smn** [comment]
odd, I didn't expect this PR to get unsquashed if I continued on my own fork 😂  Oh well.

**Comment by smn** [comment]
With this config image are published to https://hub.docker.com/r/sdehaan/rapidpro-docker/, once merged we'll need to point it at a Docker hub repo name we're more happy with.

**Comment by smn** [comment]
@stefanfoulis @tobiasmcnulty this seems to be working well enough though the most recent releases seem to break on some things:

```Invalid template /rapidpro/templates/flows/flow_runs_partial.haml: 'flows' is not a registered tag library. ```

And on a migration:

```
django.db.utils.ProgrammingError: relation "locations_adminboundary" already exists
```

I've got it setup to build automatically every 24 hours on travis.

Thoughts on landing this?

**Comment by smn** [comment]
Spoke to @rowanseymour about the migrations failure, this was due to the migrations being squashed in the 3.0 release. I cleared the cached database schema and the latest tag is now built as well: https://hub.docker.com/r/sdehaan/rapidpro-docker/tags/

**Comment by smn** [comment]
the `:latest` tag is now also published to docker hub, it always points at the latest built release.

**Comment by tobiasmcnulty** [comment]
I looked this over and the changes look good to me. Thanks @smn. I can double check this again to make sure it runs on our AWS infrastructure, or I'm happy to see it merged and then raise a PR if there are any issues -- your call.

**Comment by smn** [comment]
Thanks! I'm in favour of merging and then raising new issues as they arise.

**Comment by smn** [comment]
One of the things needing to change post merging is having this publish to the docker hub as rapidpro/rapidpro-docker.

We may want to consider having it available as `rapidpro/rapidpro` instead though. I'll create a separate issue to discuss that.

**Comment by tobiasmcnulty** [comment]
I thought I had that setup properly already (docker repo name doesn't need
to match github), but feel free to adjust if not.

**Pull request merged**
